'use strict';
var sequelize=require('./_database').sequelize();

var Country = sequelize.import('./country.js');
var Area = sequelize.import('./area.js');
var Province = sequelize.import('./province.js');
var City = sequelize.import('./city.js');
var Region = sequelize.import('./region.js');
var Popedom = sequelize.import('./popedom.js');
var User = sequelize.import('./user.js');
var Book = sequelize.import('./book.js');
var Login_Info = sequelize.import('./login_info.js');
var Activity = sequelize.import('./activity.js');
var Activity_Detail = sequelize.import('./activity_detail.js');
var Activity_Prize = sequelize.import('./activity_prize.js');
var Activity_Prize_Detail = sequelize.import('./activity_prize_detail.js');
var Activity_Get_Prize = sequelize.import('./activity_get_prize.js');
var Activity_Partake = sequelize.import('./activity_partake.js');
var Activity_Partake_Detail = sequelize.import('./activity_partake_detail.js');
var Activity_Questions = sequelize.import('./activity_questions.js');
var Activity_Seat = sequelize.import('./activity_seat.js');
var Prizerule = sequelize.import('./prizerule.js');
var Prizerule_Detail = sequelize.import('./prizerule_detail.js');
var ConstGroupSet = sequelize.import('./constgroupset.js');
var Sponsor = sequelize.import('./sponsor.js');
var Wechat_Login_Info = sequelize.import('./wechat_login_info.js');
var Login = sequelize.import('./login.js');
var Adviertisement = sequelize.import('./adviertisement.js');
var Adviertisement_Relevance = sequelize.import('./adviertisement_relevance.js');
var Webmenu = sequelize.import('./webmenu.js');
var Articles = sequelize.import('./articles.js');
var Tags = sequelize.import('./tags.js');
var Tags_Record = sequelize.import('./tags_record.js');
var Prize_Distribute = sequelize.import('./prize_distribute.js');
var Prize_Distribute_Award = sequelize.import('./prize_distribute_award.js');
var Prize_Distribute_Affiche = sequelize.import('./prize_distribute_affiche.js');
var SysAccount = sequelize.import('./sysaccount.js');
var Prize_Distribute_Plan = sequelize.import('./prize_distribute_plan.js');
var Prize_Investigation = sequelize.import('./prize_investigation.js');
var Prize_Investigation_Questions = sequelize.import('./prize_investigation_questions.js');
var User_Advice = sequelize.import('./user_advice.js');
var Wechat_User_Info = sequelize.import('./wechat_user_info.js');
var Prizeissue_Info = sequelize.import('./prizeissue_info.js');
var Luck_Activity_List = sequelize.import('./luck_activity_list.js');
var Luck_User_Order = sequelize.import('./luck_user_order.js');
var Luck_User_Order_Detail = sequelize.import('./luck_user_order_detail.js');
var Sys_Payment_Mode = sequelize.import('./sys_payment_mode.js');
var User_Invoice = sequelize.import('./user_invoice.js');
var User_Receipt_Address = sequelize.import('./user_receipt_address.js');
var Luck_Shopping_Cart = sequelize.import('./luck_shopping_cart.js');
var Luck_Bask_Order = sequelize.import('./luck_bask_order.js');
var Luck_Bask_Order_Images = sequelize.import('./luck_bask_order_images.js');
var Luck_Prize_Affiche = sequelize.import('./luck_prize_affiche.js');
var Luck_Prize_Time_Record = sequelize.import('./luck_prize_time_record.js');
var Messages = sequelize.import('./messages.js');
var Sys_Goods_Class = sequelize.import('./sys_goods_class.js');
var Drs_Resources = sequelize.import('./drs_resources.js');
var Sys_File_Mime = sequelize.import('./sys_file_mime.js');
var Drs_Image_Resources = sequelize.import('./drs_image_resources.js');
var Drs_Audios_Resources = sequelize.import('./drs_audios_resources.js');
var Drs_Control_Resources = sequelize.import('./drs_control_resources.js');
var Sys_Html_Template = sequelize.import('./sys_html_template.js');
var Info_Comment = sequelize.import('./info_comment.js');



// 建立模型之间的关系
Country.hasMany(Area);
Area.hasMany(Region);
Activity.hasMany(Activity_Detail);
Activity.hasMany(Activity_Get_Prize);
Activity.hasMany(Activity_Prize);
Activity.hasMany(Activity_Partake);
Activity.hasMany(Activity_Partake_Detail);
Activity.hasMany(Activity_Questions);
Activity.hasMany(Activity_Seat);
User.hasMany(Login_Info);
Activity_Prize.hasMany(Activity_Prize_Detail);
Adviertisement.hasMany(Adviertisement_Relevance);
Prize_Investigation.hasMany(Prize_Investigation_Questions);



// 同步模型到数据库中
// sequelize.sync();

exports.Country = Country;
exports.Area = Area;
exports.Province = Province;
exports.City = City;
exports.Region = Region;
exports.Popedom = Popedom;
exports.User = User;
exports.Book = Book;
exports.Login_Info = Login_Info;
exports.Activity = Activity;
exports.Activity_Detail = Activity_Detail;
exports.Activity_Prize = Activity_Prize;
exports.Activity_Prize_Detail = Activity_Prize_Detail;
exports.Activity_Get_Prize = Activity_Get_Prize;
exports.Activity_Partake = Activity_Partake;
exports.Activity_Partake_Detail = Activity_Partake_Detail;
exports.Activity_Questions = Activity_Questions;
exports.Activity_Seat = Activity_Seat;
exports.Prizerule = Prizerule;
exports.Prizerule_Detail = Prizerule_Detail;
exports.ConstGroupSet = ConstGroupSet;
exports.Sponsor = Sponsor;
exports.Wechat_Login_Info = Wechat_Login_Info;
exports.Login = Login;
exports.Adviertisement = Adviertisement;
exports.Adviertisement_Relevance = Adviertisement_Relevance;
exports.Webmenu = Webmenu;
exports.Articles = Articles;
exports.Tags = Tags;
exports.Tags_Record = Tags_Record;
exports.Prize_Distribute = Prize_Distribute;
exports.Prize_Distribute_Award = Prize_Distribute_Award;
exports.Prize_Distribute_Affiche = Prize_Distribute_Affiche;
exports.SysAccount = SysAccount;
exports.Prize_Distribute_Plan = Prize_Distribute_Plan;
exports.Prize_Investigation = Prize_Investigation;
exports.Prize_Investigation_Questions = Prize_Investigation_Questions;
exports.User_Advice = User_Advice;
exports.Wechat_User_Info = Wechat_User_Info;
exports.Prizeissue_Info = Prizeissue_Info;
exports.Luck_Activity_List = Luck_Activity_List;
exports.Luck_User_Order = Luck_User_Order;
exports.Luck_User_Order_Detail = Luck_User_Order_Detail;
exports.Sys_Payment_Mode = Sys_Payment_Mode;
exports.User_Invoice = User_Invoice;
exports.User_Receipt_Address = User_Receipt_Address;
exports.Luck_Shopping_Cart = Luck_Shopping_Cart;
exports.Luck_Bask_Order = Luck_Bask_Order;
exports.Luck_Bask_Order_Images = Luck_Bask_Order_Images;
exports.Luck_Bask_Order_Images = Luck_Prize_Affiche;
exports.Luck_Bask_Order_Images = Luck_Prize_Time_Record;
exports.Luck_Bask_Order_Images = Messages;
exports.Luck_Bask_Order_Images = Sys_Goods_Class;
exports.Drs_Resources = Drs_Resources;
exports.Sys_File_Mime = Sys_File_Mime;
exports.Drs_Image_Resources = Drs_Image_Resources;
exports.Drs_Audios_Resources = Drs_Audios_Resources;
exports.Drs_Control_Resources = Drs_Control_Resources;
exports.Sys_Html_Template = Sys_Html_Template;
exports.Info_Comment = Info_Comment;
